- id: gh-actions-updater
  name: gh-actions-updater
  description: Autofix GitHub Actions references to available latest-tag updates.
  entry: gau --update
  language: rust
  pass_filenames: false
  stages: [pre-commit]
